### ISSUE TITLE
Druid Connection pool shuts down once close is called and connection is not set even after calling connect again

### ISSUE THREAD

**Issue by gsratti** [zapr-oss/druidry#54] opened 2018-10-09 04:51 UTC
I have an api which does something like this :
runDruidQuery(DruidQuery query)
{
DruidConfiguration config = DruidConfiguration.builder().host(appConfig.getDruidHost())
                .port(appConfig.getDruidPort()).endpoint(appConfig.getDruidEndpoint()).build();
        client = new DruidJerseyClient(config);
        client .connect();
       client.query(query);
       client.close();

}
This api works fine for the first time. But on second call I get :
in.zapr.druid.druidry.client.exception.QueryException: javax.ws.rs.ProcessingException: java.lang.IllegalStateException: Connection pool shut down

I tried removing close() call.  On doing this, second call works, but I get the exception randomly after some time.
Do I need to configure some timeout configuration anywhere?

**Comment by nihit-zapr** [comment] 2018-10-15 07:43
@gsratti I am unable to produce the issue. Is the any specific thing that you might have missed in this issue? Can you give more information on the issue? 

I have never faced this issue with jersey but sometimes due to some issue in our system (mine is mackbook pro) some processes are closed by os. I have faced this with Aerospike client. Run you code and check on what exact module connection pool is shutting down.

**Comment by gsRatti1** [comment] 2018-10-15 09:37
Can you tell me what exactly client.connect() does? What I understood from the code is that it doesn't make any connection, but just configures connection pool.
So, can I connect just once, and keep on querying?

Regarding reproducing the issue:
I followed exact steps which have been listed in the tutorial.

What I am doing :
I have a method which does :
client.connect(), client.query() and client.close() in sequence.
When this method is called for the second time, client.query() fails giving the above mentioned exception.
If I remove close() call from the method, ie., my method just has: 
client.connect(), client.query()
In this case, I get the exception not on second call, but randomly after some calls.

Note: client is declared as global.

What I have done now :
 I am not calling connect every time in my method. 
client.connect() is called globally just once.
In my method, I just call client.query(). With these changes, I am not getting any connection exception.

But I am really not understanding how this works, and if  there is any way to specify timeout etc, as to when the client to close the connection.

**Comment by nihit-zapr** [comment] 2018-10-15 10:35
@gsratti This is how we recommend to use DruidClient. Call connect once in the application and use the same druidClient for all your queries. Close the connection when you are shutting down your application. 

Now for whats happens when you create a client, call connect, call query?
When you create a client, all the required parameters are set. When you call connect it creates a connection with the url you have mentioned in config and keeps the connection. When you call query it make a post request to the the config's specified url. After the query the connection doesn't get closed. The connection is open. You can use the same druidClient to make other queries too without closing and opening it every-time.

But if you have multiple druid servers with different url which you want to query from, in that case you need to make one druid client for each druid server.

Regarding your timeout issue, I don't think there is a way to specify client close timeout in anyway. We might need to dig into jerseyClient to find if there is close timeout. Could you specify a scenario where you need to close client based on time?

**Comment by gsRatti1** [comment] 2018-10-17 08:47
Yes, you can close this. Thanks.

**Closed** 2018-10-24 03:50 UTC
Labels: bug
